development:
  adapter: postgresql
  database: beatsfm_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: beatsfm_test
  host: localhost
  pool: 5
  timeout: 5000

 production:
  adapter: sqlite3
  database: db/production.sqlite3
  adapter: postgresql
  database: beatsfm
  host: localhost
  pool: 5
  timeout: 5000
