development:
  adapter: postgresql
  database: beatsfm_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: beatsfm_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: beatsfm
  host: localhost
  pool: 5
  timeout: 5000